apiVersion: v1
kind: Service
metadata:
  labels:
  {{- include "labels" . | nindent 4}}
    app.kubernetes.io/managed-by: Helm
  name: {{.Release.Name}}-service
spec:
{{- with .Values.Service}}
  ports:
  - port: {{.Port}} 
    protocol: TCP
    targetPort: {{.TargetPort}}
{{end}}
  selector:
   {{- include "labels" . | nindent 6 }}